modLoader="javafml" #mandatory

loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="Public Domain"

issueTrackerURL="" #optional

[[mods]] #mandatory

modId="forgecef" #mandatory

version="1.0.0" #mandatory

displayName="MCEF" #mandatory

displayURL="https://github.com/Mysticpasta1/mcef-forge" #optional

logoFile= "" #optional

credits="" #optional

authors="Mysticpasta1, WaterPicker, Montoyo, javaarchive" #optional

description='''
'''

[[dependencies.forgecef]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[43,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.forgecef]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.19.3)"
ordering="NONE"
side="BOTH"